//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IshbulatovGlazza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }

        public int SalesforYear //продажи за год высчитывается просто складывая количество продукта из таблицы продукт для каждой продажи
        {
            get
            {
                int s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    TimeSpan timeDifference = DateTime.Today.Date - p.SaleDate.Date;
                    if ((int)timeDifference.TotalDays <= 365)
                        s += p.ProductCount;
                }
                return s;
            }
        }
        public decimal Sales //сумма продаж высчитывается складывая стоимость каждой продажи
        {
            get
            {
                decimal s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    s += p.Stoimost;
                }
                return s;
            }
        }

        public int Discount //используется для расчета процентов по скидке на основе суммы продаж
        {
            get
            {
                if (Sales >= 500000)
                    return 25;
                if (Sales >= 150000)
                    return 20;
                if (Sales >= 50000)
                    return 10;
                if (Sales >= 1000)
                    return 5;
                return 0;
            }
        }

        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
        public string AgentText { get; internal set; }
    }
}
